boundos:insideBaseDirEval: return true if baseDir is "/"
go-git/go-billy pull request #48
Opened 2024-04-16 22:27 UTC by rminnich

insideBaseDirEval would fail if baseDir was "/".
Since "/" contains anything, and can never be a symlink, just return true, nil if baseDir is "/".

Add a simple test for this case.

Also, while we are at it, have the returned error be a lot more informative: show the name and the base diectory; further, have it wrap os.ErrNotExist should anyone wish to use errors.Is at some point.

2024-04-17 16:35 UTC, rminnich commented
I'll fix these tests, they really should be updated to use errors.Is. 

need to see how to do that in the context of this test framework.

2024-04-19 16:47 UTC, pjbgf requested changes
Just a small nit, otherwise LGTM.

2024-04-19 16:47 UTC, pjbgf commented on osfs/os_bound.go
> +		return false, fmt.Errorf("%q path outside base dir %q:%w", filename, fs.baseDir, os.ErrNotExist)
```suggestion
		return false, fmt.Errorf("%q path outside base dir %q: %w", filename, fs.baseDir, os.ErrNotExist)
```

2024-04-19 16:47 UTC, pjbgf commented
> I'll fix these tests, they really should be updated to use errors.Is.

@rminnich Feel free to add a commit to that effect or do a follow-up PR.

2024-04-27 14:55 UTC, rminnich commented on osfs/os_bound.go
> +		return false, fmt.Errorf("%q path outside base dir %q:%w", filename, fs.baseDir, os.ErrNotExist)
done, thanks.

2024-04-28 19:30 UTC, pjbgf approved these changes

2024-04-28 19:30 UTC, merged

2024-04-28 19:31 UTC, pjbgf commented
Thank you @rminnich! :bow:

2024-05-16 20:44 UTC, rminnich commented
Fixes #42